"""Stable package surface for deterministic event-thread mechanics."""

from .cross_temporal import (
    generate_full_summary,
    generate_scale_summary,
    get_thread_tree,
    get_threads_at_scale,
    get_unmerged_threads,
    register_appearance,
    register_batch,
    resolve_scale,
    resolve_thread,
    rollup,
    trace_chain,
    trace_thread,
)
from .event_thread import (
    EventThread,
    TimelineEntry,
    add_update,
    archive_resolved,
    compute_thread_status,
    create_thread,
    evaluate_thread_lifecycle,
    evolve_threads,
    generate_watch_queries,
    jaccard_similarity,
    lifecycle_diagnostics,
    match_cluster_to_thread,
    should_archive,
)
from .lifecycle_policy import LifecycleConfig, LifecycleDecision, ThreadLifecycleScorer

__all__ = [
    "EventThread",
    "LifecycleConfig",
    "LifecycleDecision",
    "ThreadLifecycleScorer",
    "TimelineEntry",
    "add_update",
    "archive_resolved",
    "compute_thread_status",
    "create_thread",
    "evaluate_thread_lifecycle",
    "evolve_threads",
    "generate_full_summary",
    "generate_scale_summary",
    "generate_watch_queries",
    "get_thread_tree",
    "get_threads_at_scale",
    "get_unmerged_threads",
    "jaccard_similarity",
    "lifecycle_diagnostics",
    "match_cluster_to_thread",
    "register_appearance",
    "register_batch",
    "resolve_scale",
    "resolve_thread",
    "rollup",
    "should_archive",
    "trace_chain",
    "trace_thread",
]
